
WARNING: Dataset not found, nonexistent paths: ['C:\\Users\\zhang\\Desktop\\study\\isoltor_grsammer\\yolov5_obb-master\\dataset\\dataset_demo\\dataset\\dataset_demo\\val.txt']
Traceback (most recent call last):
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\train.py", line 633, in <module>
    main(opt)
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\train.py", line 87, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\utils\loggers\__init__.py", line 76, in __init__
    self.wandb = WandbLogger(self.opt, run_id)
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\utils\loggers\wandb\wandb_utils.py", line 180, in __init__
    self.data_dict = check_wandb_dataset(opt.data)
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\utils\loggers\wandb\wandb_utils.py", line 56, in check_wandb_dataset
    return check_dataset(data_file)
  File "C:\Users\zhang\Desktop\study\isoltor_grsammer\yolov5_obb-master\utils\general.py", line 418, in check_dataset
    raise Exception('Dataset not found.')
Exception: Dataset not found.